
INSERT INTO Category(categoryId,categoryName) VALUES ('1001','Ice Cream & Frozen Yogurt');
INSERT INTO Category(categoryId,categoryName) VALUES ('1002','Seafood');
INSERT INTO Category(categoryId,categoryName) VALUES ('1003','Fast Food');
INSERT INTO Category(categoryId,categoryName) VALUES ('1004','Latin American');
INSERT INTO Category(categoryId,categoryName) VALUES ('1005','Cajun/Creole');
INSERT INTO Category(categoryId,categoryName) VALUES ('1006','Desserts');
INSERT INTO Category(categoryId,categoryName) VALUES ('1007','Mexican');
INSERT INTO Category(categoryId,categoryName) VALUES ('1008','Venezuelan');
INSERT INTO Category(categoryId,categoryName) VALUES ('1009','Coffee & Tea');
INSERT INTO Category(categoryId,categoryName) VALUES ('1010','Breakfast & Brunch');
INSERT INTO Category(categoryId,categoryName) VALUES ('1011','Indian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1012','Sandwiches');
INSERT INTO Category(categoryId,categoryName) VALUES ('1013','Food Trucks');
INSERT INTO Category(categoryId,categoryName) VALUES ('1014','Caribbean');
INSERT INTO Category(categoryId,categoryName) VALUES ('1015','Barbeque');
INSERT INTO Category(categoryId,categoryName) VALUES ('1016','Pizza');
INSERT INTO Category(categoryId,categoryName) VALUES ('1017','Chicken Wings');
INSERT INTO Category(categoryId,categoryName) VALUES ('1018','Tex-Mex');
INSERT INTO Category(categoryId,categoryName) VALUES ('1019','Food Tours');
INSERT INTO Category(categoryId,categoryName) VALUES ('1020','Burgers');
INSERT INTO Category(categoryId,categoryName) VALUES ('1021','Donuts');
INSERT INTO Category(categoryId,categoryName) VALUES ('1022','Gas Stations');
INSERT INTO Category(categoryId,categoryName) VALUES ('1023','Bakeries');
INSERT INTO Category(categoryId,categoryName) VALUES ('1024','Tours');
INSERT INTO Category(categoryId,categoryName) VALUES ('1025','Amusement Parks');
INSERT INTO Category(categoryId,categoryName) VALUES ('1026','Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1027','African');
INSERT INTO Category(categoryId,categoryName) VALUES ('1028','Chinese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1029','Peruvian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1030','Italian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1031','Vietnamese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1032','Delis');
INSERT INTO Category(categoryId,categoryName) VALUES ('1033','Breweries');
INSERT INTO Category(categoryId,categoryName) VALUES ('1034','Juice Bars & Smoothies');
INSERT INTO Category(categoryId,categoryName) VALUES ('1035','Salad');
INSERT INTO Category(categoryId,categoryName) VALUES ('1036','American (Traditional)');
INSERT INTO Category(categoryId,categoryName) VALUES ('1037','Parks');
INSERT INTO Category(categoryId,categoryName) VALUES ('1038','Asian Fusion');
INSERT INTO Category(categoryId,categoryName) VALUES ('1039','Southern');
INSERT INTO Category(categoryId,categoryName) VALUES ('1040','Street Vendors');
INSERT INTO Category(categoryId,categoryName) VALUES ('1041','Korean');
INSERT INTO Category(categoryId,categoryName) VALUES ('1042','American (New)');
INSERT INTO Category(categoryId,categoryName) VALUES ('1043','Beer, Wine & Spirits');
INSERT INTO Category(categoryId,categoryName) VALUES ('1044','Filipino');
INSERT INTO Category(categoryId,categoryName) VALUES ('1045','Diners');
INSERT INTO Category(categoryId,categoryName) VALUES ('1046','Sushi Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1047','Convenience Stores');
INSERT INTO Category(categoryId,categoryName) VALUES ('1048','Cafeteria');
INSERT INTO Category(categoryId,categoryName) VALUES ('1049','Festivals');
INSERT INTO Category(categoryId,categoryName) VALUES ('1050','Restaurants');
INSERT INTO Category(categoryId,categoryName) VALUES ('1051','Landmarks & Historical Buildings');
INSERT INTO Category(categoryId,categoryName) VALUES ('1052','Cafes');
INSERT INTO Category(categoryId,categoryName) VALUES ('1053','Museums');
INSERT INTO Category(categoryId,categoryName) VALUES ('1054','Vegan');
INSERT INTO Category(categoryId,categoryName) VALUES ('1055','Tacos');
INSERT INTO Category(categoryId,categoryName) VALUES ('1056','Zoos');
INSERT INTO Category(categoryId,categoryName) VALUES ('1057','Golf');
INSERT INTO Category(categoryId,categoryName) VALUES ('1058','Dog Parks');
INSERT INTO Category(categoryId,categoryName) VALUES ('1059','Spanish');
INSERT INTO Category(categoryId,categoryName) VALUES ('1060','Hiking');
INSERT INTO Category(categoryId,categoryName) VALUES ('1061','Local Flavor');
INSERT INTO Category(categoryId,categoryName) VALUES ('1062','Caterers');
INSERT INTO Category(categoryId,categoryName) VALUES ('1063','Cupcakes');
INSERT INTO Category(categoryId,categoryName) VALUES ('1064','Chicken Shop');
INSERT INTO Category(categoryId,categoryName) VALUES ('1065','Salvadoran');
INSERT INTO Category(categoryId,categoryName) VALUES ('1066','Japanese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1067','Steakhouses');
INSERT INTO Category(categoryId,categoryName) VALUES ('1068','Comfort Food');
INSERT INTO Category(categoryId,categoryName) VALUES ('1069','Seafood Markets');
INSERT INTO Category(categoryId,categoryName) VALUES ('1070','Noodles');
INSERT INTO Category(categoryId,categoryName) VALUES ('1071','Party & Event Planning');
INSERT INTO Category(categoryId,categoryName) VALUES ('1072','Tennis');
INSERT INTO Category(categoryId,categoryName) VALUES ('1073','Country Clubs');
INSERT INTO Category(categoryId,categoryName) VALUES ('1074','Swimming Pools');
INSERT INTO Category(categoryId,categoryName) VALUES ('1075','Custom Cakes');
INSERT INTO Category(categoryId,categoryName) VALUES ('1076','Sports Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1077','Baseball Fields');
INSERT INTO Category(categoryId,categoryName) VALUES ('1078','Physical Therapy');
INSERT INTO Category(categoryId,categoryName) VALUES ('1079','Soul Food');
INSERT INTO Category(categoryId,categoryName) VALUES ('1080','Buffets');
INSERT INTO Category(categoryId,categoryName) VALUES ('1081','Hookah Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1082','Lounges');
INSERT INTO Category(categoryId,categoryName) VALUES ('1083','Mediterranean');
INSERT INTO Category(categoryId,categoryName) VALUES ('1084','Pakistani');
INSERT INTO Category(categoryId,categoryName) VALUES ('1085','Lebanese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1086','Hot Dogs');
INSERT INTO Category(categoryId,categoryName) VALUES ('1087','Turkish');
INSERT INTO Category(categoryId,categoryName) VALUES ('1088','Dinner Theater');
INSERT INTO Category(categoryId,categoryName) VALUES ('1089','Wine Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1090','Thai');
INSERT INTO Category(categoryId,categoryName) VALUES ('1091','Soup');
INSERT INTO Category(categoryId,categoryName) VALUES ('1092','Dim Sum');
INSERT INTO Category(categoryId,categoryName) VALUES ('1093','Bubble Tea');
INSERT INTO Category(categoryId,categoryName) VALUES ('1094','Tuscan');
INSERT INTO Category(categoryId,categoryName) VALUES ('1095','Music Venues');
INSERT INTO Category(categoryId,categoryName) VALUES ('1096','Bagels');
INSERT INTO Category(categoryId,categoryName) VALUES ('1097','Cheesesteaks');
INSERT INTO Category(categoryId,categoryName) VALUES ('1098','Meat Shops');
INSERT INTO Category(categoryId,categoryName) VALUES ('1099','Pubs');
INSERT INTO Category(categoryId,categoryName) VALUES ('1100','Scandinavian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1101','Brazilian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1102','Boating');
INSERT INTO Category(categoryId,categoryName) VALUES ('1103','Lakes');
INSERT INTO Category(categoryId,categoryName) VALUES ('1104','Martial Arts');
INSERT INTO Category(categoryId,categoryName) VALUES ('1105','Health Markets');
INSERT INTO Category(categoryId,categoryName) VALUES ('1106','Hotels');
INSERT INTO Category(categoryId,categoryName) VALUES ('1107','Arcades');
INSERT INTO Category(categoryId,categoryName) VALUES ('1108','Golf Equipment');
INSERT INTO Category(categoryId,categoryName) VALUES ('1109','Gastropubs');
INSERT INTO Category(categoryId,categoryName) VALUES ('1110','Candy Stores');
INSERT INTO Category(categoryId,categoryName) VALUES ('1111','Puerto Rican');
INSERT INTO Category(categoryId,categoryName) VALUES ('1112','Hot Pot');
INSERT INTO Category(categoryId,categoryName) VALUES ('1113','Dive Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1114','Grocery');
INSERT INTO Category(categoryId,categoryName) VALUES ('1115','Irish');
INSERT INTO Category(categoryId,categoryName) VALUES ('1116','Greek');
INSERT INTO Category(categoryId,categoryName) VALUES ('1117','Beer Bar');
INSERT INTO Category(categoryId,categoryName) VALUES ('1118','Szechuan');
INSERT INTO Category(categoryId,categoryName) VALUES ('1119','Yelp Events');
INSERT INTO Category(categoryId,categoryName) VALUES ('1120','Pet Adoption');
INSERT INTO Category(categoryId,categoryName) VALUES ('1121','Education');
INSERT INTO Category(categoryId,categoryName) VALUES ('1122','Dance Clubs');
INSERT INTO Category(categoryId,categoryName) VALUES ('1123','Specialty Food');
INSERT INTO Category(categoryId,categoryName) VALUES ('1124','French');
INSERT INTO Category(categoryId,categoryName) VALUES ('1125','Food Stands');
INSERT INTO Category(categoryId,categoryName) VALUES ('1126','Karaoke');
INSERT INTO Category(categoryId,categoryName) VALUES ('1127','Vegetarian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1128','Cooking Classes');
INSERT INTO Category(categoryId,categoryName) VALUES ('1129','Art Museums');
INSERT INTO Category(categoryId,categoryName) VALUES ('1130','Guest Houses');
INSERT INTO Category(categoryId,categoryName) VALUES ('1131','Portuguese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1132','Skate Parks');
INSERT INTO Category(categoryId,categoryName) VALUES ('1133','Dominican');
INSERT INTO Category(categoryId,categoryName) VALUES ('1134','Ethiopian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1135','Polish');
INSERT INTO Category(categoryId,categoryName) VALUES ('1136','Kosher');
INSERT INTO Category(categoryId,categoryName) VALUES ('1137','Halal');
INSERT INTO Category(categoryId,categoryName) VALUES ('1138','Ramen');
INSERT INTO Category(categoryId,categoryName) VALUES ('1139','Tapas Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1140','Tapas/Small Plates');
INSERT INTO Category(categoryId,categoryName) VALUES ('1141','Wedding Planning');
INSERT INTO Category(categoryId,categoryName) VALUES ('1142','Colombian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1143','Coffee Roasteries');
INSERT INTO Category(categoryId,categoryName) VALUES ('1144','Cuban');
INSERT INTO Category(categoryId,categoryName) VALUES ('1145','New Mexican Cuisine');
INSERT INTO Category(categoryId,categoryName) VALUES ('1146','Afghan');
INSERT INTO Category(categoryId,categoryName) VALUES ('1147','Botanical Gardens');
INSERT INTO Category(categoryId,categoryName) VALUES ('1148','Laotian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1149','Jazz & Blues');
INSERT INTO Category(categoryId,categoryName) VALUES ('1150','Fish & Chips');
INSERT INTO Category(categoryId,categoryName) VALUES ('1151','Bowling');
INSERT INTO Category(categoryId,categoryName) VALUES ('1152','Florists');
INSERT INTO Category(categoryId,categoryName) VALUES ('1153','Shaved Ice');
INSERT INTO Category(categoryId,categoryName) VALUES ('1154','Venues & Event Spaces');
INSERT INTO Category(categoryId,categoryName) VALUES ('1155','Cinema');
INSERT INTO Category(categoryId,categoryName) VALUES ('1156','Butcher');
INSERT INTO Category(categoryId,categoryName) VALUES ('1157','Gift Shops');
INSERT INTO Category(categoryId,categoryName) VALUES ('1158','Bike Rentals');
INSERT INTO Category(categoryId,categoryName) VALUES ('1159','Waffles');
INSERT INTO Category(categoryId,categoryName) VALUES ('1160','Empanadas');
INSERT INTO Category(categoryId,categoryName) VALUES ('1161','Trinidadian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1162','Poke');
INSERT INTO Category(categoryId,categoryName) VALUES ('1163','Taiwanese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1164','Cocktail Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1165','Tea Rooms');
INSERT INTO Category(categoryId,categoryName) VALUES ('1166','Creperies');
INSERT INTO Category(categoryId,categoryName) VALUES ('1167','Colleges & Universities');
INSERT INTO Category(categoryId,categoryName) VALUES ('1168','Food Court');
INSERT INTO Category(categoryId,categoryName) VALUES ('1169','Performing Arts');
INSERT INTO Category(categoryId,categoryName) VALUES ('1170','Middle Eastern');
INSERT INTO Category(categoryId,categoryName) VALUES ('1171','Pool Halls');
INSERT INTO Category(categoryId,categoryName) VALUES ('1172','Parklets');
INSERT INTO Category(categoryId,categoryName) VALUES ('1173','Senegalese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1174','Teppanyaki');
INSERT INTO Category(categoryId,categoryName) VALUES ('1175','Internet Cafes');
INSERT INTO Category(categoryId,categoryName) VALUES ('1176','International Grocery');
INSERT INTO Category(categoryId,categoryName) VALUES ('1177','Gluten-Free');
INSERT INTO Category(categoryId,categoryName) VALUES ('1178','Kebab');
INSERT INTO Category(categoryId,categoryName) VALUES ('1179','Pop-up Shops');
INSERT INTO Category(categoryId,categoryName) VALUES ('1180','Persian/Iranian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1181','Haitian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1182','Smokehouse');
INSERT INTO Category(categoryId,categoryName) VALUES ('1183','Burmese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1184','Himalayan/Nepalese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1185','Churches');
INSERT INTO Category(categoryId,categoryName) VALUES ('1186','Hong Kong Style Cafe');
INSERT INTO Category(categoryId,categoryName) VALUES ('1187','Eritrean');
INSERT INTO Category(categoryId,categoryName) VALUES ('1188','Irish Pub');
INSERT INTO Category(categoryId,categoryName) VALUES ('1189','Public Art');
INSERT INTO Category(categoryId,categoryName) VALUES ('1190','British');
INSERT INTO Category(categoryId,categoryName) VALUES ('1191','Bistros');
INSERT INTO Category(categoryId,categoryName) VALUES ('1192','Food Delivery Services');
INSERT INTO Category(categoryId,categoryName) VALUES ('1193','Airport Lounges');
INSERT INTO Category(categoryId,categoryName) VALUES ('1194','Belgian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1195','Bangladeshi');
INSERT INTO Category(categoryId,categoryName) VALUES ('1196','Gay Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1197','Aquariums');
INSERT INTO Category(categoryId,categoryName) VALUES ('1198','Honduran');
INSERT INTO Category(categoryId,categoryName) VALUES ('1199','Tobacco Shops');
INSERT INTO Category(categoryId,categoryName) VALUES ('1200','Acai Bowls');
INSERT INTO Category(categoryId,categoryName) VALUES ('1201','Argentine');
INSERT INTO Category(categoryId,categoryName) VALUES ('1202','Cigar Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1203','Nightlife');
INSERT INTO Category(categoryId,categoryName) VALUES ('1204','Cheese Shops');
INSERT INTO Category(categoryId,categoryName) VALUES ('1205','Pharmacy');
INSERT INTO Category(categoryId,categoryName) VALUES ('1206','Russian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1207','Izakaya');
INSERT INTO Category(categoryId,categoryName) VALUES ('1208','Beer Tours');
INSERT INTO Category(categoryId,categoryName) VALUES ('1209','Children''s Museums');
INSERT INTO Category(categoryId,categoryName) VALUES ('1210','Bookstores');
INSERT INTO Category(categoryId,categoryName) VALUES ('1211','Climbing');
INSERT INTO Category(categoryId,categoryName) VALUES ('1212','Cantonese');
INSERT INTO Category(categoryId,categoryName) VALUES ('1213','Distilleries');
INSERT INTO Category(categoryId,categoryName) VALUES ('1214','Basque');
INSERT INTO Category(categoryId,categoryName) VALUES ('1215','Live/Raw Food');
INSERT INTO Category(categoryId,categoryName) VALUES ('1216','German');
INSERT INTO Category(categoryId,categoryName) VALUES ('1217','Moroccan');
INSERT INTO Category(categoryId,categoryName) VALUES ('1218','Chocolatiers & Shops');
INSERT INTO Category(categoryId,categoryName) VALUES ('1219','Hawaiian');
INSERT INTO Category(categoryId,categoryName) VALUES ('1220','Vinyl Records');
INSERT INTO Category(categoryId,categoryName) VALUES ('1221','Gelato');
INSERT INTO Category(categoryId,categoryName) VALUES ('1222','Libraries');
INSERT INTO Category(categoryId,categoryName) VALUES ('1223','Brasseries');
INSERT INTO Category(categoryId,categoryName) VALUES ('1224','Falafel');
INSERT INTO Category(categoryId,categoryName) VALUES ('1225','Modern European');
INSERT INTO Category(categoryId,categoryName) VALUES ('1226','Tiki Bars');
INSERT INTO Category(categoryId,categoryName) VALUES ('1227','Art Galleries');
